"""Add is_private column to Channel model

Revision ID: c6c8479e434d
Revises: 
Create Date: 2024-11-27 15:29:47.948507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c8479e434d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.drop_column('is_private')

    # ### end Alembic commands ###
